version: '3'
services:
  aj-db:
    container_name: aj-db
    image: mysql
    volumes:
      - aj-db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password1234
      MYSQL_USER: arjun
      MYSQL_PASSWORD: Password@1234
      MYSQL_DATABASE: SPEDB

  aj-backend:
    container_name: aj-backend
    image: arjun201/aj-backend:1.0
    privileged: true
    working_dir: /aj/backend
    volumes:
      - aj-backend-vol:/aj/backend
    stdin_open: true
    expose:
      - 8086
    ports:
      - 8086:8086
    depends_on:
      - aj-db
    restart: unless-stopped
    environment:
      DB_SERVICE_NAME: aj-db
      MYSQL_DATABASE: SPEDB
      MYSQL_USER: aj
      MYSQL_PASSWORD: Password@1234
      BACKEND_INTERNAL_PORT: 8086

  aj-frontend:
    container_name: aj-frontend
    image: arjun201/aj-frontend:1.0
    working_dir: /aj/frontend
    stdin_open: true
    expose:
      - 8087
    ports:
      - 8087:80
    depends_on:
      - aj-backend
    restart: unless-stopped

volumes:
  aj-db-vol:
  aj-backend-vol:
