version: '3'
services:
  aj-db:
    container_name: aj-db
    image: mysql
    volumes:
      - aj-db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password1234
      MYSQL_USER: arjun
      MYSQL_PASSWORD: Password@1234
      MYSQL_DATABASE: SPEDB

  aj-backend:
    container_name: aj-backend
    image: arjun201/aj-backend:1.0
    privileged: true
    working_dir: /aj/backend
    volumes:
      - aj-backend-vol:/aj/backend
    stdin_open: true
    expose:
      - 8086
    ports:
      - 8086:8086
    depends_on:
      - aj-db
    restart: unless-stopped
    environment:
      DB_SERVICE_NAME: aj-db
      MYSQL_DATABASE: SPEDB
      MYSQL_USER: arjun
      MYSQL_PASSWORD: Password@1234
      BACKEND_INTERNAL_PORT: 8086
      LOGSTASH_HOST: logstash
      LOGSTASH_PORT: 5000

  aj-frontend:
    container_name: aj-frontend
    image: arjun201/aj-frontend:1.0
    working_dir: /aj/frontend
    stdin_open: true
    expose:
      - 8087
    ports:
      - 8087:80
    depends_on:
      - aj-backend
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    container_name: logstash
    volumes:
      - /home/aj/SPE_major_project/JAIRU-Frontend/logstash-pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  aj-db-vol:
  aj-backend-vol:
  esdata:
    driver: local